#MySQL is manditory for this plugin
#Login information
MySQL_host: localhost
MySQL_port: 3306
MySQL_username: root
MySQL_password: password

#Database name (doesn't require adjusting)
MySQL_database: minecraft_publicbuilds

#Tables in database (doesn't require adjusting)
MySQL_playerData: player_data
MySQL_plotData: plot_data

#Plot Limits
#Limit on maximum distance between 2 corners of a plot
plot_distance:
    guest: 25
    apprentice: 50
    jrbuilder: 75
    builder: 100
#Limit on active claimed plots

#If user is at the limit they will no longer be able to create a new plot
plot_limit:
    guest: 1
    apprentice: 2
    jrbuilder: 3
    builder: 5

#Maximum number of total plots, this includes submitted plots
plot_maximum: 15

#Server must be using multiverse to allow for multiple worlds
worlds:
    save: saveWorld
    build: buildWorld
    tutorial:
        before: tutorialBefore
        after: tutorialAfter

#Tutorial
#The user has to create a plot that includes these points
starting_position:
    x:
    y:
    z:
plot_corners:
    1:
        x: 2808086
        z: -5408457
    2:
        x: 2808111
        z: -5408432
    3:
        x: 2808093
        z: -5408415
    4:
        x: 2808068
        z: -5408440
        
tpll_points:
    1:
        x: 2808089.6
        z: -5408447.8
    2:
        x: 2808096.6
        z: -5408440.4
    3:
        x: 2808086.3
        z: -5408430.5
    4:
        x: 2808078.3
        z: -5408437.8
        
building_height: 4
tutorial_final_stage: 6

#Building points
#Points multiplier for each level
#Example if size is 3 and size_multiplier is 5 then the player will receive 3*5=15 points for size.
#This is done for each of the three categories
size_multiplier: 1
accuracy_multiplier: 1
quality_multiplier: 1

#Points multiplier
#Calculated by building points multiplied by points_multiplier
#Example the user received 15 building points and the points_multiplier is 3 then they will get 15*3=45 points.
points_multiplier: 5

#Number of days a player can be inactive before their plots get cancelled
plot_inactive_cancel: 14