#Rank limits

#Guest
#Maximum claimable area
guestArea: 400
#Maximum number of claims
guestLimit: 1

#Apprentice
#Maximum claimable area
apprenticeArea: 900
#Maximum number of claims
apprenticeLimit: 2

#Builder
#Maximum claimable area
builderArea: 1600
#Maximum number of claims
builderLimit: 3


#MySQL Info

MySQL_host: localhost
MySQL_port: 3306
MySQL_database: test
MySQL_username: root
MySQL_password: password
MySQL_plotTable: player_data
MySQL_reviewTable: review
MySQL_completeTable: completed

