name: PublicBuilds
version: 1.0
main: me.elgamer.publicbuilds.Main
description: Claiming System
depend: [WorldGuard, WorldEdit, UKnetUtilities, BTEPoints]
api-version: 1.16

commands:
    gui:
        usage: /<command> 
        description: Open the Main Gui of the plugin.
    createarea:
        usage: /<command>
        description: Creates a polygonal area in which plots can be claimed, requires a polygon selection.
    skiptutorial:
        usage: /<command>
        description: Skips the tutorial.