name: PublicBuilds
version: 1.0
main: me.elgamer.publicbuilds.Main
description: Claiming System
depend: [WorldEdit, WorldGuard, UKnetUtilities, BTEPoints]

commands:
    gui:
        usage: /<command> 
        description: Open the Main Gui of the plugin.
    corner:
        usage: /<command> 1|2|3|4
        description: Sets the corner marker for a plot.
    createarea:
        usage: /<command>
        description: Creates a polygonal area in which plots can be claimed, requires a polygon selection.
    